services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8001
