export const MALE_NAMES = [
  'Aaron',
  'Adam',
  'Adrian',
  'Alex',
  'Andrew',
  'Anthony',
  'Austin',
  'Benjamin',
  'Blake',
  'Brandon',
  'Caleb',
  'Cameron',
  'Charles',
  'Chris',
  'Connor',
  'Daniel',
  'David',
  'Diego',
  'Drew',
  'Ethan',
  'Felix',
  'Gabriel',
  'Gavin',
  'Harrison',
  'Hunter',
  'Ian',
  'Isaac',
  'Jack',
  'Jacob',
  'James',
  'Jason',
  'Jordan',
  'Jose',
  'Joshua',
  'Kevin',
  'Leo',
  'Liam',
  'Logan',
  'Lucas',
  'Mark',
  'Mason',
  'Matthew',
  'Michael',
  'Nathan',
  'Nicholas',
  'Noah',
  'Oliver',
  'Owen',
  'Parker',
  'Patrick',
  'Quinn',
  'Robert',
  'Ryan',
  'Samuel',
  'Sebastian',
  'Thomas',
  'Tyler',
  'Victor',
  'William',
  'Zachary',
];

export const FEMALE_NAMES = [
  'Abigail',
  'Addison',
  'Alexandra',
  'Aria',
  'Avery',
  'Bella',
  'Brooke',
  'Casey',
  'Charlotte',
  'Chloe',
  'Dakota',
  'Elena',
  'Elizabeth',
  'Emily',
  'Emma',
  'Gabriella',
  'Grace',
  'Hannah',
  'Harper',
  'Isabella',
  'Jamie',
  'Jessica',
  'Julia',
  'Katherine',
  'Kimberly',
  'Lauren',
  'Lily',
  'Madison',
  'Maria',
  'Maya',
  'Megan',
  'Michelle',
  'Morgan',
  'Natalie',
  'Nicole',
  'Olivia',
  'Paige',
  'Phoenix',
  'Quinn',
  'Rachel',
  'Riley',
  'Sage',
  'Samantha',
  'Sarah',
  'Sophia',
  'Stephanie',
  'Sydney',
  'Taylor',
  'Victoria',
  'Zoe',
];

// Display text options for each core trait level (5 levels: very low, low, medium, high, very high)
export const TRAIT_DISPLAY_WORDS = {
  openness: {
    veryLow: ['Ultra-traditional', 'Deeply conservative', 'Rigid', 'Old-fashioned', 'Inflexible'],
    low: ['Traditional', 'Conservative', 'Routine-loving', 'Conventional', 'Steady', 'Cautious'],
    medium: ['Balanced', 'Moderate', 'Open-minded', 'Adaptable', 'Reasonable', 'Flexible'],
    high: ['Adventurous', 'Explorer', 'Risk-taker', 'Free-spirited', 'Curious', 'Creative', 'Bold'],
    veryHigh: ['Trendsetter', 'Extreme adventurer', 'Revolutionary', 'Fearless pioneer'],
  },
  sportiness: {
    veryLow: ['Couch potato', 'Sedentary', 'Exercise-averse', 'Inactive', 'Lazy'],
    low: ['Relaxed', 'Indoor-person', 'Low-energy', 'Peaceful', 'Leisurely'],
    medium: ['Active', 'Casual athlete', 'Moderately fit', 'Weekend warrior', 'Sporty', 'Healthy'],
    high: [
      'Athlete',
      'Fitness enthusiast',
      'Sports lover',
      'Gym regular',
      'Competitive',
      'Strong',
      'Energetic',
    ],
    veryHigh: [
      'Elite athlete',
      'Fitness freak',
      'Powerlifter',
      'Marathon runner',
      'Sports addict',
      'Beast-mode',
      'Peak performer',
    ],
  },
  social: {
    veryLow: ['Hermit', 'Extremely introverted', 'Reclusive', 'Solitary', 'Loner', 'Withdrawn'],
    low: [
      'Introverted',
      'Homebody',
      'Quiet',
      'Private',
      'Thoughtful',
      'Reserved',
      'Shy',
      'Introspective',
    ],
    medium: ['Social', 'Friendly', 'Outgoing', 'Approachable', 'Personable', 'Warm', 'Sociable'],
    high: [
      'Party lover',
      'Social butterfly',
      'People person',
      'Extroverted',
      'Charismatic',
      'Talkative',
      'Popular',
    ],
    veryHigh: [
      'Party animal',
      'Super extrovert',
      'Social dynamo',
      'Life of party',
      'Spotlight seeker',
      'Social magnet',
    ],
  },
  natural: {
    veryLow: [
      'High-maintenance',
      'Glamour queen',
      'Luxury lover',
      'Primped',
      'Polished perfection',
      'Image-focused',
    ],
    low: [
      'Glamorous',
      'Stylish',
      'Fashion-forward',
      'Polished',
      'Well-groomed',
      'Sophisticated',
      'Refined',
    ],
    medium: ['Casual', 'Comfortable', 'Easygoing', 'Practical', 'Relaxed style', 'Laid-back'],
    high: [
      'Natural',
      'Down-to-earth',
      'Low-maintenance',
      'Authentic',
      'Unpretentious',
      'Simple',
      'Real',
    ],
    veryHigh: [
      'Ultra-natural',
      'Minimalist',
      'Raw',
      'Unfiltered',
      'Completely authentic',
      'Zero-fuss',
      'Pure',
    ],
  },
};

export const MISC_DISPLAY_WORDS = {
  cats: { positive: ['Cat lover', 'Feline friend'], negative: ['Dog-only person'] },
  dogs: { positive: ['Dog lover', 'Puppy person'], negative: ['Cat-only person'] },
  smoking: { positive: ['Smoker'], negative: ['Non-smoker'] },
  drinking: {
    positive: ['Social drinker', 'Wine enthusiast'],
    negative: ['Teetotaler', 'Sober lifestyle'],
  },
  travel: {
    positive: ['Wanderlust', 'Travel addict', 'Globetrotter'],
    negative: ['Stay-at-home type'],
  },
  cooking: {
    positive: ['Foodie', 'Home chef', 'Kitchen wizard'],
    negative: ['Takeout specialist'],
  },
  reading: { positive: ['Bookworm', 'Reader', 'Literary type'], negative: ['Audio-visual person'] },
  music: { positive: ['Music lover', 'Melody seeker'], negative: ['Silence preferer'] },
  movies: { positive: ['Film buff', 'Cinema lover'], negative: ['Book over movie'] },
  outdoors: {
    positive: ['Nature lover', 'Outdoorsy', 'Fresh-air seeker'],
    negative: ['Indoor enthusiast'],
  },
};