export const MALE_NAMES = [
  'Aaron',
  'Adam',
  'Adrian',
  'Alex',
  'Andrew',
  'Anthony',
  'Austin',
  'Benjamin',
  'Blake',
  'Brandon',
  'Caleb',
  'Cameron',
  'Charles',
  'Chris',
  'Connor',
  'Daniel',
  'David',
  'Diego',
  'Drew',
  'Ethan',
  'Felix',
  'Gabriel',
  'Gavin',
  'Harrison',
  'Hunter',
  'Ian',
  'Isaac',
  'Jack',
  'Jacob',
  'James',
  'Jason',
  'Jordan',
  'Jose',
  'Joshua',
  'Kevin',
  'Leo',
  'Liam',
  'Logan',
  'Lucas',
  'Mark',
  'Mason',
  'Matthew',
  'Michael',
  'Nathan',
  'Nicholas',
  'Noah',
  'Oliver',
  'Owen',
  'Parker',
  'Patrick',
  'Quinn',
  'Robert',
  'Ryan',
  'Samuel',
  'Sebastian',
  'Thomas',
  'Tyler',
  'Victor',
  'William',
  'Zachary',
];

export const FEMALE_NAMES = [
  'Abigail',
  'Addison',
  'Alexandra',
  'Aria',
  'Avery',
  'Bella',
  'Brooke',
  'Casey',
  'Charlotte',
  'Chloe',
  'Dakota',
  'Elena',
  'Elizabeth',
  'Emily',
  'Emma',
  'Gabriella',
  'Grace',
  'Hannah',
  'Harper',
  'Isabella',
  'Jamie',
  'Jessica',
  'Julia',
  'Katherine',
  'Kimberly',
  'Lauren',
  'Lily',
  'Madison',
  'Maria',
  'Maya',
  'Megan',
  'Michelle',
  'Morgan',
  'Natalie',
  'Nicole',
  'Olivia',
  'Paige',
  'Phoenix',
  'Quinn',
  'Rachel',
  'Riley',
  'Sage',
  'Samantha',
  'Sarah',
  'Sophia',
  'Stephanie',
  'Sydney',
  'Taylor',
  'Victoria',
  'Zoe',
];

// Display text options for each core trait level (5 levels: very low, low, medium, high, very high)
export const TRAIT_DISPLAY_WORDS = {
  openness: {
    veryLow: ['Ultra-traditional', 'Deeply conservative', 'Rigid', 'Old-fashioned', 'Inflexible'],
    low: ['Traditional', 'Conservative', 'Routine-loving', 'Conventional', 'Steady', 'Cautious'],
    medium: ['Balanced', 'Moderate', 'Open-minded', 'Adaptable', 'Reasonable', 'Flexible'],
    high: ['Adventurous', 'Explorer', 'Risk-taker', 'Free-spirited', 'Curious', 'Creative', 'Bold'],
    veryHigh: ['Trendsetter', 'Extreme adventurer', 'Revolutionary', 'Fearless pioneer'],
  },
  sportiness: {
    veryLow: ['Couch potato', 'Sedentary', 'Exercise-averse', 'Inactive', 'Lazy'],
    low: ['Relaxed', 'Indoor-person', 'Low-energy', 'Peaceful', 'Leisurely'],
    medium: ['Active', 'Casual athlete', 'Moderately fit', 'Weekend warrior', 'Sporty', 'Healthy'],
    high: [
      'Athlete',
      'Fitness enthusiast',
      'Sports lover',
      'Gym regular',
      'Competitive',
      'Strong',
      'Energetic',
    ],
    veryHigh: [
      'Elite athlete',
      'Fitness freak',
      'Powerlifter',
      'Marathon runner',
      'Sports addict',
      'Beast-mode',
      'Peak performer',
    ],
  },
  social: {
    veryLow: ['Hermit', 'Extremely introverted', 'Reclusive', 'Solitary', 'Loner', 'Withdrawn'],
    low: [
      'Introverted',
      'Homebody',
      'Quiet',
      'Private',
      'Thoughtful',
      'Reserved',
      'Shy',
      'Introspective',
    ],
    medium: ['Social', 'Friendly', 'Outgoing', 'Approachable', 'Personable', 'Warm', 'Sociable'],
    high: [
      'Party lover',
      'Social butterfly',
      'People person',
      'Extroverted',
      'Charismatic',
      'Talkative',
      'Popular',
    ],
    veryHigh: [
      'Party animal',
      'Super extrovert',
      'Social dynamo',
      'Life of party',
      'Spotlight seeker',
      'Social magnet',
    ],
  },
  natural: {
    veryLow: [
      'High-maintenance',
      'Glamour queen',
      'Luxury lover',
      'Primped',
      'Polished perfection',
      'Image-focused',
    ],
    low: [
      'Glamorous',
      'Stylish',
      'Fashion-forward',
      'Polished',
      'Well-groomed',
      'Sophisticated',
      'Refined',
    ],
    medium: ['Casual', 'Comfortable', 'Easygoing', 'Practical', 'Relaxed style', 'Laid-back'],
    high: [
      'Natural',
      'Down-to-earth',
      'Low-maintenance',
      'Authentic',
      'Unpretentious',
      'Simple',
      'Real',
    ],
    veryHigh: [
      'Ultra-natural',
      'Minimalist',
      'Raw',
      'Unfiltered',
      'Completely authentic',
      'Zero-fuss',
      'Pure',
    ],
  },
};

export const MISC_DISPLAY_WORDS = {
  cats: { positive: ['Cat lover', 'Feline friend'], negative: ['Dislikes cats'] },
  dogs: { positive: ['Dog lover', 'Puppy person'], negative: ['Dislikes dogs'] },
  smoking: { positive: ['Smoker'], negative: ['Non-smoker'] },
  drinking: {
    positive: ['Social drinker', 'Wine enthusiast'],
    negative: ['Teetotaler', 'Sober lifestyle'],
  },
  travel: {
    positive: ['Wanderlust', 'Travel addict', 'Globetrotter'],
    negative: ['Scared of flying'],
  },
  cooking: {
    positive: ['Foodie', 'Home chef', 'Kitchen wizard'],
    negative: ['Takeout specialist'],
  },
  reading: { positive: ['Bookworm', 'Reader', 'Literary type'], negative: ['Book hater'] },
  music: { positive: ['Music lover', 'Melody seeker'], negative: ['Music hater'] },
  movies: { positive: ['Film buff', 'Cinema lover'], negative: ['Movie hater'] },
  outdoors: {
    positive: ['Nature lover', 'Outdoorsy', 'Fresh-air seeker'],
    negative: ['Indoor enthusiast'],
  },
};


// {person1} and {person2} are replaced with actual names
export const COUPLE_MESSAGES = {
  veryPositive: [
    '{person1} and {person2} get along splendidly.',
    '{person1} and {person2} share a hearty laugh.',
    '{person2} compliments {person1}\'s outfit.',
    '{person1} and {person2} plan a next meeting.',
    '{person1} and {person2} seem to click instantly.',
    '{person2} offers to walk {person1} home.',
    '{person1} and {person2} discover they love the same book.',
    '{person2} makes {person1} smile brightly.',
    '{person1} and {person2} talk for hours without pause.',
    '{person1} feels completely at ease with {person2}.',
  ],
  positive: [
    '{person1} and {person2} have an engaging conversation.',
    '{person2} finds {person1}\'s stories interesting.',
    '{person1} and {person2} share a moment of connection.',
    '{person2} appreciates {person1}\'s sense of humor.',
    '{person1} and {person2} seem comfortable together.',
    '{person1} enjoys {person2}\'s company.',
    '{person2} listens attentively to {person1}.',
    '{person1} and {person2} find common ground.',
    '{person2} makes {person1} feel heard.',
    '{person1} and {person2} have good chemistry.',
  ],
  neutral: [
    '{person1} and {person2} have a polite conversation.',
    '{person2} asks {person1} about their hobbies.',
    '{person1} and {person2} discuss the weather.',
    '{person2} offers {person1} a menu suggestion.',
    '{person1} and {person2} sit quietly for a moment.',
    '{person1} checks their phone briefly.',
    '{person2} stirs their drink thoughtfully.',
    '{person1} and {person2} comment on the music.',
    '{person2} asks {person1} about work.',
    '{person1} and {person2} watch people walk by.',
    '{person1} and {person2} order their drinks.',
    '{person2} compliments the cafe atmosphere.',
    '{person1} mentions they like this neighborhood.',
    '{person2} talks about their weekend plans.',
    '{person1} and {person2} agree the coffee is good.',
    '{person1} asks {person2} about their commute.',
    '{person2} shares a story about their pet.',
    '{person1} and {person2} laugh at something mild.',
    '{person2} mentions a book they\'re reading.',
    '{person1} talks about their favorite restaurants.',
    '{person1} and {person2} discuss current events briefly.',
    '{person2} asks about {person1}\'s family.',
    '{person1} mentions they enjoy this type of music.',
    '{person2} talks about their job casually.',
    '{person1} and {person2} comment on the weather again.',
    '{person1} asks {person2} about their interests.',
    '{person2} mentions they like the coffee here.',
    '{person1} and {person2} have a comfortable silence.',
    '{person2} asks if {person1} comes here often.',
    '{person1} talks about their morning routine.',
  ],
  negative: [
    '{person1} and {person2} don\'t have a lot to talk about.',
    '{person1} feels a bit nervous around {person2}.',
    '{person2} seems distracted during their chat.',
    '{person1} and {person2} have different opinions.',
    '{person2} checks the time discreetly.',
    '{person1} struggles to find conversation topics.',
    '{person2} looks around the room occasionally.',
    '{person1} and {person2} have an awkward pause.',
    '{person1} feels the conversation is stalling.',
    '{person2} seems a bit reserved.',
  ],
  veryNegative: [
    '{person1} and {person2} get into a disagreement.',
    '{person1} feels quite uncomfortable around {person2}.',
    '{person2} seems uninterested in what {person1} says.',
    '{person1} and {person2} run out of things to discuss.',
    '{person2} appears bored during their conversation.',
    '{person1} and {person2} have conflicting views.',
    '{person1} wishes the meeting would end soon.',
    '{person2} frequently glances at the exit.',
    '{person1} and {person2} sit in uncomfortable silence.',
    '{person1} feels no spark with {person2}.',
  ],
};