export const LETTER_SETS = [
  {
    letters: ['A', 'E', 'R', 'T', 'U', 'N', 'C'],
    validWords: [
      'CARE',
      'RACE',
      'ACRE',
      'TEAR',
      'RATE',
      'NEAR',
      'CURE',
      'CRANE',
      'NATURE',
      'REACT',
      'TRACE',
      'CANTER',
    ],
  },
  {
    letters: ['S', 'P', 'I', 'R', 'E', 'D', 'N'],
    validWords: [
      'SPIRE',
      'PRIDE',
      'SPINE',
      'SNIPE',
      'PINES',
      'SPEND',
      'SPIDER',
      'INSIDE',
      'SIGNED',
      'SPINED',
    ],
  },
  {
    letters: ['L', 'O', 'V', 'E', 'R', 'S', 'T'],
    validWords: [
      'LOVE',
      'OVER',
      'ROSE',
      'VEST',
      'REST',
      'LOST',
      'SOLVER',
      'LOVERS',
      'REVOLT',
      'STOVER',
    ],
  },
  {
    letters: ['M', 'A', 'G', 'I', 'C', 'L', 'N'],
    validWords: [
      'MAGIC',
      'CALM',
      'CLAIM',
      'MAIN',
      'CLAM',
      'MAIL',
      'CLINICAL',
      'MAGICAL',
      'CLANG',
      'MANIC',
    ],
  },
  {
    letters: ['B', 'R', 'O', 'W', 'N', 'E', 'D'],
    validWords: [
      'BROWN',
      'OWNER',
      'DRONE',
      'BORED',
      'BOWER',
      'WONDER',
      'BROWNED',
      'BORROWED',
      'DOWNER',
      'BONDER',
    ],
  },
];